Import("env")

env.Replace(LIBS=[])

env.Program(
    target="algorithms/spot_prediction/tst_reeke_model",
    source="algorithms/spot_prediction/tst_reeke_model.cc",
)
env.Program(
    target="algorithms/spatial_indexing/tst_quadtree",
    source="algorithms/spatial_indexing/tst_quadtree.cc",
)
env.Program(
    target="algorithms/spatial_indexing/tst_octree",
    source="algorithms/spatial_indexing/tst_octree.cc",
)
env.Program(
    target="algorithms/spatial_indexing/tst_collision_detection",
    source="algorithms/spatial_indexing/tst_collision_detection.cc",
)

# Use google tests while I'm self-developing
conf = env.Configure()
flag = conf.TryCompile("#include <gtest/gtest.h>", extension=".cpp")
if flag:
    env.Program(
        target="algorithms/spot_finding/test_imageset_spotfinder",
        source="algorithms/spot_finding/test_imageset_spotfinder.cc",
        LIBS=["gtest_main", "gtest"],
    )
