language: cpp
os:
  - linux
  - osx

env:
  - BOOST_VERSION=1.56.0

# Don't build the travis branch
branches:
  except:
    - travis

addons:
  apt:
    packages: 
      - libhdf5-dev
      - libeigen3-dev
      - libtiff5-dev
      # - libboost-python-dev # We want to control boost version explicitly now
cache:
  directories:
    # - ${TRAVIS_BUILD_DIR}/deps/cmake
    - ${TRAVIS_BUILD_DIR}/build # Cache the whole build directory for incremental builds
    - ${TRAVIS_BUILD_DIR}/deps # Other dependencies like boost, cmake will be installed here

before_install:
  - python --version
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null;
      export HOMEBREW_NO_AUTO_UPDATE=1
    fi

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Setup default versions and override compiler if needed
  ############################################################################
  - if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.56.0; fi

  # Install/upgrade homebrew dependencies; [pcre libtiff] exist already
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      for package in hdf5 cmake eigen; do
        if brew ls --versions $package > /dev/null; then
          brew outdated $package || brew upgrade $package
        else
          brew install $package
        fi
      done
      # We want special options for this one so custom install
      brew install findutils --with-default-names
    fi
  

  ############################################################################
  # Build/Install specified boost version with boost-python
  ############################################################################
  - |
    if [[ "${BOOST_VERSION}" != "" ]]; then
      BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
      BOOST_BUILD_DIR=~/build_tmp/boost
      if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
        if [[ "${BOOST_VERSION}" == "trunk" ]]; then
          BOOST_URL="http://github.com/boostorg/boost.git"
          travis_retry git clone --depth 1 --recursive ${BOOST_URL} ${BOOST_BUILD_DIR} || exit 1
        else
          BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
          mkdir -p ${BOOST_BUILD_DIR}
          { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_BUILD_DIR}; } || exit 1
        fi
        mkdir -p ${BOOST_DIR}
        (cd ${BOOST_BUILD_DIR} && ./bootstrap.sh && ./b2 -j 3 --prefix=${BOOST_DIR} --with-python install) || exit 1
      fi
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
    fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - cmake --version | head -n1


  # Other python libs we know about
  - pip install mock docopt pathlib2 enum34 pyyaml

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  # Move the current repository into a dials subdirectory
  - mkdir dials && mv $(git ls-tree --name-only HEAD) dials && mv .git dials/
  # Verify what our folder looks like
  - ls
  # Grab the autobuild repository
  - git clone https://github.com/ndevenish/autobuild.git cmake
  # Install the scons conversion repository
  - pip install git+https://github.com/ndevenish/read_scons.git
  # Get all the other modules we need to compile
  - python prepare_singlemodule.py --write-log

  # Generate the CMakelists
  - tbx2cmake . cmake/autogen/autogen.yaml .

  # Handle timestamp updating from the cache. Since travis gives a fresh checkout
  # every time, all files in the repository will be newer than the build cache dates,
  # and so everything will be rebuilt anyway. This backdates things that haven't changed.
  - | 
    if [[ -f build/commit_ids.txt ]]; then
      # Use the old module list; any new modules won't need to be touched anyway
      MODULES=$(cat build/commit_ids.txt | awk '{ print $1; }')
      # Find the oldest time in the build directory
      echo "Oldest time: "
      find -type f -printf '%T+ %p\n' | sort | head -n 1

      OLDEST_MTIME=$(find . -type f -printf "%.10T@\n" | sort | head -n 1)
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        echo "Backdating to $(date -d @$OLDEST_MTIME)"
        OLDEST_TS=$(date -d @$OLDEST_MTIME +%Y%m%d%H%M.%S)
      else
        echo "Backdating to $(date -r $OLDEST_MTIME)"
        OLDEST_TS=$(date -r $OLDEST_MTIME +%Y%m%d%H%M.%S)
      fi

      # Change the mtime of ALL checked out files to match this
      for repo in $MODULES; do
        echo "  Handling cache backdate for $repo"
        # Find the old commit and if it exists in the repository, we can backdate
        OLDREV=$(cat commit_ids.txt | grep "${repo} " | awk '{ print $2; }')
        if GIT_DIR=$repo/.git git cat-file -e $OLDREV; then
          # The commit exists. Backdate everything...
          find $repo | xargs touch -t $OLDEST_TS
          # And then forward-date everything that has changed
          GIT_DIR=$repo/.git git diff --name-only | xargs touch -c
        else
          echo "  Commit $OLDREV does not exist in repository; not backdating"
        fi
      done
    else
      echo "No build/commit_ids.txt; Not syncing timestamps"
    fi
    # Finally, replace the old commit id file
    mkdir -p build
    mv commit_ids.txt build/


  # Do the actual building
  - mkdir -p build
  - cd build
  - cmake .. ${CMAKE_OPTIONS}

script:
  - make -j 3

