language: c++
dist: xenial
# os:
#   - linux
#   - osx

env:
  - BOOST_VERSION=1.63.0
#  - BOOST_VERSION=1.65.1

matrix:
  allow_failures:
    - env: BOOST_VERSION=1.65.1

# Don't build the travis branch
branches:
  only:
    - tmaster

addons:
  apt:
    packages:
      - libhdf5-dev
      - libeigen3-dev
      - libtiff5-dev
      - libmsgpack-dev
      # - sshpass
cache:
  timeout: 1000
  directories:
    - ${TRAVIS_BUILD_DIR}/build # Cache the whole build directory for incremental builds
    - ${TRAVIS_BUILD_DIR}/deps # Other dependencies like boost, cmake will be installed here

jobs:
  include:
    - stage: Build
      os: linux
      install:
        - . .travis/prepare_environment.sh
      before_script:
        - ${TRAVIS_BUILD_DIR}/dials/.travis/prepare_build.sh
        - cd ${TRAVIS_BUILD_DIR}/build && cmake .. ${CMAKE_OPTIONS}
      script:
        # - echo travis:$SSH_PASSWD | sudo chpasswd
        # - sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
        # - sudo service ssh restart
        # # - sudo apt-get install sshpass
        # - sshpass -p $SSH_PASSWD ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travis@home.ndevenish.com
        - cd ${TRAVIS_BUILD_DIR}/build
        - travis_timeout make -j 3
      after_success:
        # Put a marker so that we know we had a successful complete build
        - touch build_complete
    - stage: Build
      os: osx
      osx_image: xcode10.1
      install:
        - . .travis/prepare_environment.sh
      before_script:
        - ${TRAVIS_BUILD_DIR}/dials/.travis/prepare_build.sh
        - cd ${TRAVIS_BUILD_DIR}/build && cmake .. ${CMAKE_OPTIONS}
      script:
        - cd ${TRAVIS_BUILD_DIR}/build
        - travis_timeout make -j 3
      after_success:
        # Put a marker so that we know we had a successful complete build
        - touch build_complete

    - stage: Test
      os: linux
      install:
        - . .travis/prepare_environment.sh
      before_script:
        - ${TRAVIS_BUILD_DIR}/dials/.travis/prepare_build.sh
        - cd ${TRAVIS_BUILD_DIR}/build && cmake .. ${CMAKE_OPTIONS}
        - cd ${TRAVIS_BUILD_DIR}/build
        - travis_timeout make -j 3
      script:
        - export PATH=${TRAVIS_BUILD_DIR}/build/bin:$PATH
        - which pytest
        - pytest -ra -n 2 ../dials
    - stage: Test
      os: osx
      osx_image: xcode10.1
      install:
        - . .travis/prepare_environment.sh
      before_script:
        - ${TRAVIS_BUILD_DIR}/dials/.travis/prepare_build.sh
        - cd ${TRAVIS_BUILD_DIR}/build && cmake .. ${CMAKE_OPTIONS}
        - cd ${TRAVIS_BUILD_DIR}/build
        - travis_timeout make -j 3
      script:
        - export PATH=${TRAVIS_BUILD_DIR}/build/bin:$PATH
        - which pytest
        - pytest -ra -n 2 ../dials

stages:
  - Build
  - Test

# install:
#   - . .travis/prepare_environment.sh

# before_script:
#   - ${TRAVIS_BUILD_DIR}/dials/.travis/prepare_build.sh
#   - cd ${TRAVIS_BUILD_DIR}/build && cmake .. ${CMAKE_OPTIONS}

# script:
#   - cd ${TRAVIS_BUILD_DIR}/build
#   - travis_timeout make -j 3

# after_success:
#   # Put a marker so that we know we had a successful complete build
#   - touch build_complete
